[package]
name = "from-req-1"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.1"
config = "0.13"
dotenv = "0.15"
env_logger = "0.9"
lazy_static = "1.4"
regex = "1.6"
serde = { version = "1.0", features = ["derive"] }
